# -*- coding: utf-8 -*-
import spacy
# Form implementation generated from reading ui file 'UI_PROT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PIL import Image
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QApplication, QGraphicsScene, QGraphicsView, QGraphicsPixmapItem
from PyQt5.QtGui import QPixmap
import Combos
import NewLDA
import tools
import Words
import Vectors

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import NMF
from random import randint as rnd
import NewLDA

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        self.VectorMap = {}
        self.searchEngine = tools.InternetParser.SearchEngine()
        self.ocr = tools.OCR.OCR("D:/NLP_GI/Tesseract-OCR/tesseract.exe")
        self.en_model = spacy.load("en_core_web_lg")
        self.ru_model = spacy.load("ru_core_news_lg")
        self.models = {"Английская модель": ("en", self.en_model), "Русская модель": ("ru", self.ru_model)}
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 867)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1121, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 195, 731))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)

        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Английская модель", "Русская модель"])

        self.verticalLayout_2.addWidget(self.comboBox)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)


        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(860, 370, 471, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 441, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 431, 371))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 40, 441, 301))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 10, 441, 22))
        self.horizontalSlider.setAcceptDrops(False)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tabWidget.addTab(self.tab_3, "")

        self.tab_Vectors = QtWidgets.QWidget()
        self.tab_Vectors.setObjectName("tab_Vectors")
        self.LineEditVectors = QtWidgets.QLineEdit(self.tab_Vectors)
        self.LineEditVectors.setGeometry(QtCore.QRect(10, 10, 351, 22))
        self.LineEditVectors.setObjectName("lineEditVectors")
        self.ButtonVectors = QtWidgets.QPushButton(self.tab_Vectors)
        self.ButtonVectors.setGeometry(QtCore.QRect(370, 10, 81, 21))
        self.ButtonVectors.setObjectName("buttonVectors")
        self.TextVectors = QtWidgets.QTextEdit(self.tab_Vectors)
        self.TextVectors.setGeometry(QtCore.QRect(10, 40, 441, 301))
        self.TextVectors.setObjectName("TextVectors")
        self.tabWidget.addTab(self.tab_Vectors, "")

        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_7)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 10, 431, 22))
        self.horizontalSlider_2.setMaximum(10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 40, 441, 301))
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 10, 441, 331))
        self.textEdit_5.setObjectName("textEdit_5")
        self.tabWidget.addTab(self.tab_8, "")

        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(860, 70, 471, 301))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 441, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 441, 141))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_7.setGeometry(QtCore.QRect(200, 10, 131, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 481, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 70, 471, 161))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(330, 10, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget_2.addTab(self.tab_5, "")

        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 80, 641, 731))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(910, 790, 250, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(910, 770, 400, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1392, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_4.clicked.connect(self.FileChoiceDialogue)
        self.pushButton_5.clicked.connect(self.route)
        self.ButtonVectors.clicked.connect(self.FindVector)
        self.pushButton_7.clicked.connect(self.AskDeepSeek)
        self.pushButton_8.clicked.connect(self.RouteParser)
        self.pushButton.clicked.connect(self.save)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_4.setText(_translate("MainWindow", "Thematical analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Thematical Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "NER"))
        self.checkBox_5.setText(_translate("MainWindow", "Named entry recognition"))
        self.ButtonVectors.setText(_translate("MainWindow", "Найти"))
        self.pushButton_4.setText(_translate("MainWindow", "Файл"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.checkBox_2.setText(_translate("MainWindow", "Words"))
        self.checkBox_3.setText(_translate("MainWindow", "Vectors"))
        self.checkBox.setText(_translate("MainWindow", "Combos"))
        self.checkBox_4.setText(_translate("MainWindow", "Thematical analysis"))
        self.checkBox_5.setText(_translate("MainWindow", "Named entry recognition"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "График"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Words"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Combos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Vectors), _translate("MainWindow", "Vectors"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 1"))
        self.checkBox_6.setText(_translate("MainWindow", "Наукоментрические базы"))
        self.checkBox_7.setText(_translate("MainWindow", "Отзывы на вузы"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Tab 2"))
        self.label.setText(_translate("MainWindow", "Кол-во слов:"))
        self.label_2.setText(_translate("MainWindow", "Время потраченное на выполнение запроса:"))

    def count_words_in_file(self, file_path):
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()
            words = text.split()
            return len(words)

    def FileChoiceDialogue(self):
        filename, smth = QFileDialog.getOpenFileName(None, "Выберите файл", "", "All Files (*);;Text Files (*.txt)")
        print(filename, smth)
        type = filename.split(".")[-1]
        if type == "pdf":
            lang, model = self.GetModelLang(self.comboBox.currentText())
            print(lang)
            if lang == "ru":
                print("entered ru")
                self.ocr.ConvertPDF("rus", filename, "".join(type))
                print("exited ru")
            if lang == "en":
                print("entered en")
                self.ocr.ConvertPDF("eng", filename, "".join(type))
                print("exited en")
            filename = "".join(type) + ".txt"
        with open(filename, mode="r", encoding="utf-8") as f:
            self.textEdit_2.setText(f.read())
        self.label.setText(f"Кол-во слов: {self.count_words_in_file(filename)}")

    def ParsePoly(self):
        self.lineEdit.setText("Московский политех")
        self.textBrowser_4.setText(self.FormatPolytechData(tools.PolytechParser.ParsePolytechData()))

    def FormatPolytechData(self, data):
        text = "\n\n".join(data)
        return text

    def FormatInternet(self, results):
        text = ""
        print("entered Format")
        for title, link, snippet in results:
            text += title + "\n" + link + "\n" + snippet + "\n\n"
        print(text)
        return text

    def ShowGraph(self):
        lang, model = self.GetModelLang(self.comboBox.currentText())
        NLP = spacy.load(model)
        SortedText, SortedTextVectors = self.GraphDataCollection()
        print(SortedText)
        print(list(SortedText))
        tools.PlottingGraph.PlottingGraph(TextInput=list(SortedText.keys()), TextVectors=SortedTextVectors)
        pixmap = QPixmap("graph.png")
        scene = QGraphicsScene()
        item = QGraphicsPixmapItem(pixmap)
        scene.addItem(item)
        self.graphicsView.setScene(scene)
        self.graphicsView.fitInView(item, Qt.KeepAspectRatio)
        img = Image.open("graph.png")
        img.show()


    def ParseInternet(self):
        text = self.lineEdit.text()
        print(text)
        results = self.searchEngine.getResultsByKeyword(text, 0)
        print(results)
        self.textBrowser_4.setText(self.FormatInternet(self.searchEngine.getResultsByKeyword(text, 0)))

    def save_text_to_file(self, text):
        with open("saved.txt", 'w', encoding='utf-8') as file:
            file.write(text)

    def save(self):
        text = self.textEdit_2.toPlainText()
        self.save_text_to_file(text)

    def RouteParser(self):
        if self.checkBox_7.isChecked():
            print("poly")
            self.ParsePoly()
        else:
            print("cool")
            self.ParseInternet()

    def GetModelLang(self, text):
        print(text)
        if text[0] == "А":
            return ("en", "en_core_web_lg")
        return ("ru", "ru_core_news_lg")

    def FormatWords(self, wordsFreq, back=""):
        formatedText = ""
        for word, freq in wordsFreq.items():
            formatedText += str(word) + ": " + str(freq) + back + "\n"
        return formatedText

    def FormatCombos(self, combosFreq):
        print(type(combosFreq))
        formatedText = ""
        for combo, freq in combosFreq.items():
            print(combo)
            formatedText += " ".join(list(combo)) + ": " + str(freq) + "\n"
        return formatedText

    def ApplyWords(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        wordsFreq = Words.Words(text, spacy.load(model), lang)
        self.textBrowser_2.setText(self.FormatWords(wordsFreq))

    def GraphDataCollection(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        NLP = spacy.load(model)
        SortedText = Words.Words(text, NLP, lang)
        SortedTextVectors = [NLP(word).vector for word in SortedText]  # List of Numpy arrays
        return (SortedText, SortedTextVectors)

    def ApplyVectors(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        self.VectorMap = Vectors.VectorsPrecalc(text, spacy.load(model), lang)

    def FindVector(self):
        WordToFindSimilar = self.LineEditVectors.text()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        self.TextVectors.setText(self.FormatWords(Vectors.Vectors(self.VectorMap, spacy.load(model), WordToFindSimilar), "%"))

    def ApplyCombos(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        comboNumber = self.horizontalSlider.value()
        print(comboNumber)
        sortedCombos = Combos.Combos(text, spacy.load(model), lang, comboNumber)
        self.textBrowser_3.setText(self.FormatCombos(sortedCombos))

    def ApplyTA(self):
        text = self.textEdit_2.toPlainText()
        num_topics = self.horizontalSlider_2.value()
        self.textEdit_4.setText(NewLDA.NewLDA(text, num_topics))

    def ApplyNER(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.GetModelLang(self.comboBox.currentText())
        self.textEdit_5.setText(tools.NamedEntryRecognition.ner(text, spacy.load(model)))

    def AskDeepSeek(self):
        self.textEdit.setText(tools.DeepSeekRequest.requestDeepSeek(self.plainTextEdit.toPlainText()))
    def route(self):
        if self.checkBox_2.isChecked():
            self.ApplyWords()
        if self.checkBox_3.isChecked():
            self.ApplyVectors()
        if self.checkBox.isChecked():
            self.ApplyCombos()
        if self.checkBox_4.isChecked():
            self.ApplyTA()
        if self.checkBox_5.isChecked():
            self.ApplyNER()
        self.ShowGraph()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
