import spacy
# Form implementation generated from reading ui file 'UI_PROT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PIL import Image
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QApplication, QGraphicsScene, QGraphicsView, QGraphicsPixmapItem
from PyQt5.QtGui import QPixmap
import Combos
import NewLDA
import tools
import Words
import Vectors

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import NMF
from random import randint as rnd
import NewLDA


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.VectorMap = {}
                self.searchEngine = tools.InternetParser.SearchEngine()
                self.ocr = tools.OCR.OCR("D:/NLP_GI/Tesseract-OCR/tesseract.exe")
                self.en_model = spacy.load("en_core_web_lg")
                self.ru_model = spacy.load("ru_core_news_lg")
                self.models = {"Английская модель": ("en", self.en_model), "Русская модель": ("ru", self.ru_model)}

                MainWindow.setObjectName("MainWindow")
                MainWindow.setEnabled(True)
                MainWindow.resize(1191, 894)
                MainWindow.setStyleSheet("background-color: rgb(188, 210, 238);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
                self.tabWidget.setGeometry(QtCore.QRect(630, 380, 591, 491))
                self.tabWidget.setStyleSheet("border-color: rgb(218, 234, 255);\n"
                                             "border: 1px;")
                self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
                self.tabWidget.setObjectName("tabWidget")
                self.tab = QtWidgets.QWidget()
                self.tab.setObjectName("tab")
                self.graphicsView = QtWidgets.QGraphicsView(self.tab)
                self.graphicsView.setGeometry(QtCore.QRect(0, 10, 531, 371))
                self.graphicsView.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.graphicsView.setObjectName("graphicsView")
                self.tabWidget.addTab(self.tab, "")
                self.tab_2 = QtWidgets.QWidget()
                self.tab_2.setObjectName("tab_2")
                self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
                self.textBrowser_2.setGeometry(QtCore.QRect(0, 10, 531, 371))
                self.textBrowser_2.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                                 "")
                self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.textBrowser_2.setObjectName("textBrowser_2")
                self.tabWidget.addTab(self.tab_2, "")
                self.tab_3 = QtWidgets.QWidget()
                self.tab_3.setObjectName("tab_3")
                self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
                self.textBrowser_3.setGeometry(QtCore.QRect(0, 40, 531, 341))
                self.textBrowser_3.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                                 "")
                self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.textBrowser_3.setObjectName("textBrowser_3")
                self.horizontalSlider = QtWidgets.QSlider(self.tab_3)
                self.horizontalSlider.setGeometry(QtCore.QRect(10, 10, 521, 22))
                self.horizontalSlider.setAcceptDrops(False)
                self.horizontalSlider.setMaximum(10)
                self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
                self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
                self.horizontalSlider.setObjectName("horizontalSlider")
                self.tabWidget.addTab(self.tab_3, "")
                self.tab_6 = QtWidgets.QWidget()
                self.tab_6.setObjectName("tab_6")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
                self.lineEdit_2.setGeometry(QtCore.QRect(0, 10, 431, 22))
                self.lineEdit_2.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                              "\n"
                                              "")
                self.lineEdit_2.setInputMask("")
                self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.textEdit_3 = QtWidgets.QTextEdit(self.tab_6)
                self.textEdit_3.setGeometry(QtCore.QRect(0, 40, 531, 341))
                self.textEdit_3.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                              "")
                self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.textEdit_3.setObjectName("textEdit_3")
                self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
                self.pushButton_6.setGeometry(QtCore.QRect(450, 10, 81, 21))
                self.pushButton_6.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                                "")
                self.pushButton_6.setObjectName("pushButton_6")
                self.tabWidget.addTab(self.tab_6, "")
                self.tab_7 = QtWidgets.QWidget()
                self.tab_7.setObjectName("tab_7")
                self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_7)
                self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 10, 521, 22))
                self.horizontalSlider_2.setMaximum(10)
                self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
                self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
                self.horizontalSlider_2.setObjectName("horizontalSlider_2")
                self.textEdit_4 = QtWidgets.QTextEdit(self.tab_7)
                self.textEdit_4.setGeometry(QtCore.QRect(0, 40, 531, 341))
                self.textEdit_4.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                              "")
                self.textEdit_4.setObjectName("textEdit_4")
                self.tabWidget.addTab(self.tab_7, "")
                self.tab_8 = QtWidgets.QWidget()
                self.tab_8.setObjectName("tab_8")
                self.textEdit_5 = QtWidgets.QTextEdit(self.tab_8)
                self.textEdit_5.setGeometry(QtCore.QRect(0, 10, 531, 371))
                self.textEdit_5.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                              "")
                self.textEdit_5.setObjectName("textEdit_5")
                self.tabWidget.addTab(self.tab_8, "")
                self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
                self.tabWidget_2.setEnabled(True)
                self.tabWidget_2.setGeometry(QtCore.QRect(630, 100, 641, 331))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
                self.tabWidget_2.setSizePolicy(sizePolicy)
                self.tabWidget_2.setAutoFillBackground(False)
                self.tabWidget_2.setStyleSheet("border-color: rgb(218, 234, 255);\n"
                                               "border: 1px;")
                self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
                self.tabWidget_2.setIconSize(QtCore.QSize(20, 20))
                self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
                self.tabWidget_2.setUsesScrollButtons(False)
                self.tabWidget_2.setTabsClosable(False)
                self.tabWidget_2.setMovable(False)
                self.tabWidget_2.setTabBarAutoHide(False)
                self.tabWidget_2.setObjectName("tabWidget_2")
                self.tab_4 = QtWidgets.QWidget()
                self.tab_4.setStyleSheet("border-color: rgb(188, 210, 238);")
                self.tab_4.setObjectName("tab_4")
                self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_4)
                self.plainTextEdit.setGeometry(QtCore.QRect(0, 10, 531, 31))
                self.plainTextEdit.setAcceptDrops(True)
                self.plainTextEdit.setAutoFillBackground(False)
                self.plainTextEdit.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.plainTextEdit.setTabChangesFocus(False)
                self.plainTextEdit.setUndoRedoEnabled(True)
                self.plainTextEdit.setObjectName("plainTextEdit")
                self.toolButton_7 = QtWidgets.QToolButton(self.tab_4)
                self.toolButton_7.setEnabled(True)
                self.toolButton_7.setGeometry(QtCore.QRect(0, 50, 93, 21))
                self.toolButton_7.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.toolButton_7.setShortcut("")
                self.toolButton_7.setCheckable(False)
                self.toolButton_7.setObjectName("toolButton_7")
                self.textEdit = QtWidgets.QTextEdit(self.tab_4)
                self.textEdit.setGeometry(QtCore.QRect(0, 80, 531, 151))
                self.textEdit.setAcceptDrops(True)
                self.textEdit.setToolTipDuration(-1)
                self.textEdit.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.textEdit.setObjectName("textEdit")
                self.tabWidget_2.addTab(self.tab_4, "")
                self.tab_5 = QtWidgets.QWidget()
                self.tab_5.setObjectName("tab_5")
                self.checkBox_6 = QtWidgets.QCheckBox(self.tab_5)
                self.checkBox_6.setGeometry(QtCore.QRect(0, 50, 181, 20))
                self.checkBox_6.setStyleSheet("background-color: rgb(188, 210, 238);")
                self.checkBox_6.setObjectName("checkBox_6")
                self.checkBox_7 = QtWidgets.QCheckBox(self.tab_5)
                self.checkBox_7.setGeometry(QtCore.QRect(180, 50, 131, 20))
                self.checkBox_7.setStyleSheet("background-color: rgb(188, 210, 238);")
                self.checkBox_7.setObjectName("checkBox_7")
                self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_5)
                self.textBrowser_4.setGeometry(QtCore.QRect(0, 80, 531, 151))
                self.textBrowser_4.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                                 "")
                self.textBrowser_4.setObjectName("textBrowser_4")
                self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
                self.pushButton_8.setGeometry(QtCore.QRect(420, 50, 111, 21))
                self.pushButton_8.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                                "")
                self.pushButton_8.setObjectName("pushButton_8")
                self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_5)
                self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 10, 531, 31))
                self.plainTextEdit_2.setAcceptDrops(True)
                self.plainTextEdit_2.setAutoFillBackground(False)
                self.plainTextEdit_2.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.plainTextEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.plainTextEdit_2.setTabChangesFocus(False)
                self.plainTextEdit_2.setUndoRedoEnabled(True)
                self.plainTextEdit_2.setObjectName("plainTextEdit_2")
                self.tabWidget_2.addTab(self.tab_5, "")
                self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
                self.textEdit_2.setGeometry(QtCore.QRect(10, 99, 601, 731))
                self.textEdit_2.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.textEdit_2.setObjectName("textEdit_2")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(0, 0, 1191, 80))
                self.frame.setStyleSheet("background-color: rgb(66, 101, 223);")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.pushButton_7 = QtWidgets.QPushButton(self.frame)
                self.pushButton_7.setEnabled(True)
                self.pushButton_7.setGeometry(QtCore.QRect(10, 25, 71, 28))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
                self.pushButton_7.setSizePolicy(sizePolicy)
                self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                font.setStrikeOut(False)
                font.setKerning(True)
                self.pushButton_7.setFont(font)
                self.pushButton_7.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
                self.pushButton_7.setAutoFillBackground(False)
                self.pushButton_7.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.pushButton_7.setCheckable(False)
                self.pushButton_7.setAutoRepeat(False)
                self.pushButton_7.setFlat(False)
                self.pushButton_7.setObjectName("pushButton_7")
                self.pushButton_3 = QtWidgets.QPushButton(self.frame)
                self.pushButton_3.setGeometry(QtCore.QRect(90, 25, 71, 28))
                self.pushButton_3.setAutoFillBackground(False)
                self.pushButton_3.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.pushButton_3.setFlat(False)
                self.pushButton_3.setObjectName("pushButton_3")
                self.pushButton_9 = QtWidgets.QPushButton(self.frame)
                self.pushButton_9.setEnabled(True)
                self.pushButton_9.setGeometry(QtCore.QRect(170, 25, 71, 28))
                self.pushButton_9.setAutoFillBackground(False)
                self.pushButton_9.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.pushButton_9.setFlat(False)
                self.pushButton_9.setObjectName("pushButton_9")
                self.comboBox_2 = QtWidgets.QComboBox(self.frame)
                self.comboBox_2.setEnabled(True)
                self.comboBox_2.setGeometry(QtCore.QRect(250, 24, 148, 28))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
                self.comboBox_2.setSizePolicy(sizePolicy)
                self.comboBox_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.comboBox_2.setAutoFillBackground(False)
                self.comboBox_2.setStyleSheet("background-color: rgb(218, 234, 255);\n"
                                              "")
                self.comboBox_2.setEditable(False)
                self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
                self.comboBox_2.setObjectName("comboBox_2")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
                self.checkBox_8.setGeometry(QtCore.QRect(410, 25, 63, 28))
                self.checkBox_8.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.checkBox_8.setObjectName("checkBox_8")
                self.checkBox_9 = QtWidgets.QCheckBox(self.frame)
                self.checkBox_9.setGeometry(QtCore.QRect(484, 25, 76, 28))
                self.checkBox_9.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.checkBox_9.setObjectName("checkBox_9")
                self.checkBox_10 = QtWidgets.QCheckBox(self.frame)
                self.checkBox_10.setGeometry(QtCore.QRect(570, 25, 98, 28))
                self.checkBox_10.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.checkBox_10.setObjectName("checkBox_10")
                self.checkBox_11 = QtWidgets.QCheckBox(self.frame)
                self.checkBox_11.setGeometry(QtCore.QRect(680, 25, 155, 28))
                self.checkBox_11.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.checkBox_11.setObjectName("checkBox_11")
                self.checkBox_12 = QtWidgets.QCheckBox(self.frame)
                self.checkBox_12.setGeometry(QtCore.QRect(848, 25, 242, 28))
                self.checkBox_12.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.checkBox_12.setObjectName("checkBox_12")
                self.pushButton_10 = QtWidgets.QPushButton(self.frame)
                self.pushButton_10.setGeometry(QtCore.QRect(1103, 25, 71, 28))
                self.pushButton_10.setAutoFillBackground(False)
                self.pushButton_10.setStyleSheet("background-color: rgb(218, 234, 255);")
                self.pushButton_10.setFlat(False)
                self.pushButton_10.setObjectName("pushButton_10")
                self.pushButton_7.raise_()
                self.pushButton_9.raise_()
                self.comboBox_2.raise_()
                self.checkBox_8.raise_()
                self.checkBox_9.raise_()
                self.checkBox_10.raise_()
                self.checkBox_11.raise_()
                self.checkBox_12.raise_()
                self.pushButton_10.raise_()
                self.pushButton_3.raise_()
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(630, 810, 531, 20))
                self.label_2.setObjectName("label_2")
                self.tabWidget_2.raise_()
                self.tabWidget.raise_()
                self.textEdit_2.raise_()
                self.frame.raise_()
                self.label_2.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1191, 23))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.pushButton_7.clicked.connect(self.FileChoiceDialogue)
                self.pushButton_10.clicked.connect(self.route)
                self.pushButton_6.clicked.connect(self.FindVector)
                self.toolButton_7.clicked.connect(self.AskDeepSeek)
                self.pushButton_8.clicked.connect(self.RouteParser)
                self.pushButton_3.clicked.connect(self.save)

                self.retranslateUi(MainWindow)
                self.tabWidget.setCurrentIndex(4)
                self.tabWidget_2.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Вкладка 1"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Вкладка 2"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница"))
                self.pushButton_6.setText(_translate("MainWindow", "Кнопка"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Страница"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Тематический анализ"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "NER"))
                self.toolButton_7.setText(_translate("MainWindow", "Кнопка"))
                self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Вкладка 1"))
                self.checkBox_6.setText(_translate("MainWindow", "Наукоментрические базы"))
                self.checkBox_7.setText(_translate("MainWindow", "Отзывы на вузы"))
                self.pushButton_8.setText(_translate("MainWindow", "Искать"))
                self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Вкладка 2"))
                self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                 "p, li { white-space: pre-wrap; }\n"
                                                                 "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.15094pt; font-weight:400; font-style:normal;\">\n"
                                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
                self.pushButton_7.setText(_translate("MainWindow", "Файл"))
                self.pushButton_3.setText(_translate("MainWindow", "Сохранить"))
                self.pushButton_9.setText(_translate("MainWindow", "Проверка"))
                self.comboBox_2.setItemText(0, _translate("MainWindow", "Английская модель"))
                self.comboBox_2.setItemText(1, _translate("MainWindow", "Русская модель"))
                self.checkBox_8.setText(_translate("MainWindow", "Слова"))
                self.checkBox_9.setText(_translate("MainWindow", "Векторы"))
                self.checkBox_10.setText(_translate("MainWindow", "Комбинации"))
                self.checkBox_11.setText(_translate("MainWindow", "Тематический анализ"))
                self.checkBox_12.setText(_translate("MainWindow", "Распознавание именованной записи"))
                self.pushButton_10.setText(_translate("MainWindow", "Старт"))
                self.label_2.setText(_translate("MainWindow", "Кол-во слов:"))

        def count_words_in_file(self, file_path):
            try:
                with open(file_path, 'r', encoding='utf-8') as file:
                    text = file.read()
                    words = text.split()
                    return len(words)
            except:
                pass

        def FileChoiceDialogue(self):
            try:
                filename, smth = QFileDialog.getOpenFileName(None, "Выберите файл", "",
                                                             "All Files (*);;Text Files (*.txt)")
                print(filename, smth)
                type = filename.split(".")[-1]
                if type == "pdf":
                    lang, model = self.models[self.comboBox_2.currentText()]
                    print(lang)
                    if lang == "ru":
                        print("entered ru")
                        self.ocr.ConvertPDF("rus", filename, "".join(type))
                        print("exited ru")
                    if lang == "en":
                        print("entered en")
                        self.ocr.ConvertPDF("eng", filename, "".join(type))
                        print("exited en")
                    filename = "".join(type) + ".txt"
                with open(filename, mode="r", encoding="utf-8") as f:
                    self.textEdit_2.setText(f.read())
                self.label.setText(f"Кол-во слов: {self.count_words_in_file(filename)}")
            except:
                pass

        def ParsePoly(self):
            self.plainTextEdit_2.setPlainText("Московский политех")
            self.textBrowser_4.setText(self.FormatPolytechData(tools.PolytechParser.ParsePolytechData()))

        def FormatPolytechData(self, data):
            text = "\n\n".join(data)
            return text

        def FormatInternet(self, results):
            text = ""
            print("entered Format")
            for title, link, snippet in results:
                text += title + "\n" + link + "\n" + snippet + "\n\n"
            print(text)
            return text

        def ShowGraph(self):    
            lang, model = self.models[self.comboBox_2.currentText()]
            NLP = model
            SortedText, SortedTextVectors = self.GraphDataCollection()
            print(SortedText)
            print(list(SortedText))
            tools.PlottingGraph.PlottingGraph(TextInput=list(SortedText.keys()), TextVectors=SortedTextVectors)
            pixmap = QPixmap("graph.png")
            scene = QGraphicsScene()
            item = QGraphicsPixmapItem(pixmap)
            scene.addItem(item)
            self.graphicsView.setScene(scene)
            self.graphicsView.fitInView(item, Qt.KeepAspectRatio)
            img = Image.open("graph.png")
            img.show()

        def ParseInternet(self):
            text = self.plainTextEdit_2.toPlainText()
            print(text)
            results = self.searchEngine.getResultsByKeyword(text, 0)
            print(results)
            self.textBrowser_4.setText(self.FormatInternet(self.searchEngine.getResultsByKeyword(text, 0)))

        def save_text_to_file(self, text):
            with open("saved.txt", 'w', encoding='utf-8') as file:
                file.write(text)

        def save(self):
            text = self.textEdit_2.toPlainText()
            self.save_text_to_file(text)

        def RouteParser(self):
            if self.checkBox_7.isChecked():
                print("poly")
                self.ParsePoly()
            else:
                print("cool")
                self.ParseInternet()

        def GetModelLang(self, text):
            print(text)
            if text[0] == "А":
                return ("en", "en_core_web_lg")
            return ("ru", "ru_core_news_lg")

        def FormatWords(self, wordsFreq, back=""):
            formatedText = ""
            for word, freq in wordsFreq.items():
                formatedText += str(word) + ": " + str(freq) + back + "\n"
            return formatedText

        def FormatCombos(self, combosFreq):
            print(type(combosFreq))
            formatedText = ""
            for combo, freq in combosFreq.items():
                print(combo)
                formatedText += " ".join(list(combo)) + ": " + str(freq) + "\n"
            return formatedText

        def ApplyWords(self):
            text = self.textEdit_2.toPlainText()
            lang, model = self.models[self.comboBox_2.currentText()]
            wordsFreq = Words.Words(text, model, lang)
            self.textBrowser_2.setText(self.FormatWords(wordsFreq))

        def GraphDataCollection(self):
            text = self.textEdit_2.toPlainText()
            print(text)
            lang, model = self.models[self.comboBox_2.currentText()]
            NLP = model
            SortedText = Words.Words(text, NLP, lang)
            SortedTextVectors = [NLP(word).vector for word in SortedText]  # List of Numpy arrays
            return (SortedText, SortedTextVectors)

        def ApplyVectors(self):
            text = self.textEdit_2.toPlainText()
            lang, model = self.models[self.comboBox_2.currentText()]
            self.VectorMap = Vectors.VectorsPrecalc(text, model, lang)

        def FindVector(self):
            WordToFindSimilar = self.lineEdit_2.text()
            lang, model = self.models[self.comboBox_2.currentText()]
            self.textEdit_3.setText(self.FormatWords(Vectors.Vectors(self.VectorMap, model, WordToFindSimilar), "%"))

        def ApplyCombos(self):
            text = self.textEdit_2.toPlainText()
            lang, model = self.models[self.comboBox_2.currentText()]
            comboNumber = self.horizontalSlider.value()
            print(comboNumber)
            sortedCombos = Combos.Combos(text, model, lang, comboNumber)
            self.textBrowser_3.setText(self.FormatCombos(sortedCombos))

        def ApplyTA(self):
            text = self.textEdit_2.toPlainText()
            num_topics = self.horizontalSlider_2.value()
            self.textEdit_4.setText(NewLDA.NewLDA(text, num_topics))

        def ApplyNER(self):
            text = self.textEdit_2.toPlainText()
            lang, model = self.models[self.comboBox_2.currentText()]
            self.textEdit_5.setText(tools.NamedEntryRecognition.ner(text, model))

        def AskDeepSeek(self):
            self.textEdit.setText(tools.DeepSeekRequest.requestDeepSeek(self.plainTextEdit.toPlainText()))

        def route(self):
            try:
                if self.checkBox_8.isChecked():
                    self.ApplyWords()
                if self.checkBox_9.isChecked():
                    self.ApplyVectors()
                if self.checkBox_10.isChecked():
                    self.ApplyCombos()
                if self.checkBox_11.isChecked():
                    self.ApplyTA()
                if self.checkBox_12.isChecked():
                    self.ApplyNER()
                self.ShowGraph()
            except:
                pass

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
