# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_PROT_06.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-
import spacy
# Form implementation generated from reading ui file 'UI_PROT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PIL import Image
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QApplication, QGraphicsScene, QGraphicsView, QGraphicsPixmapItem
from PyQt5.QtGui import QPixmap
import Combos
import NewLDA
import tools
import Words
import Vectors

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import NMF
from random import randint as rnd
import NewLDA


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1191, 894)
        MainWindow.setStyleSheet("background-color: rgb(188, 210, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setEnabled(True)
        self.horizontalFrame.setGeometry(QtCore.QRect(0, 0, 1191, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 101, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.horizontalFrame.setPalette(palette)
        self.horizontalFrame.setStyleSheet("background-color: rgb(66, 101, 223);")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton_4.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalFrame)
        self.comboBox.setEnabled(True)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox_2.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox_3.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox_4.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox_5.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        spacerItem = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame)
        self.pushButton_5.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(630, 380, 591, 491))
        self.tabWidget.setStyleSheet("border-color: rgb(218, 234, 255);\n"
"border: 1px;")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(0, 10, 531, 371))
        self.graphicsView.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 10, 531, 371))
        self.textBrowser_2.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 40, 531, 341))
        self.textBrowser_3.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 10, 521, 22))
        self.horizontalSlider.setAcceptDrops(False)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 10, 431, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"\n"
"")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 40, 531, 341))
        self.textEdit_3.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 10, 81, 21))
        self.pushButton_6.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_7)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 10, 521, 22))
        self.horizontalSlider_2.setMaximum(10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 40, 531, 341))
        self.textEdit_4.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 10, 531, 371))
        self.textEdit_5.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.tabWidget.addTab(self.tab_8, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(630, 100, 641, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("border-color: rgb(218, 234, 255);\n"
"border: 1px;")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("border-color: rgb(188, 210, 238);")
        self.tab_4.setObjectName("tab_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 10, 531, 31))
        self.plainTextEdit.setAcceptDrops(True)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setUndoRedoEnabled(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.toolButton_7 = QtWidgets.QToolButton(self.tab_4)
        self.toolButton_7.setEnabled(True)
        self.toolButton_7.setGeometry(QtCore.QRect(0, 50, 93, 28))
        self.toolButton_7.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.toolButton_7.setShortcut("")
        self.toolButton_7.setCheckable(False)
        self.toolButton_7.setObjectName("toolButton_7")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 90, 531, 141))
        self.textEdit.setAcceptDrops(True)
        self.textEdit.setToolTipDuration(-1)
        self.textEdit.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 10, 181, 24))
        self.checkBox_6.setStyleSheet("background-color: rgb(188, 210, 238);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_7.setGeometry(QtCore.QRect(180, 10, 131, 24))
        self.checkBox_7.setStyleSheet("background-color: rgb(188, 210, 238);")
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 541, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setStyleSheet("background-color: rgb(188, 210, 238);")
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 40, 531, 191))
        self.textBrowser_4.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(320, 9, 111, 21))
        self.pushButton_8.setStyleSheet("background-color: rgb(218, 234, 255);\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 100, 601, 701))
        self.textEdit_2.setStyleSheet("background-color: rgb(218, 234, 255);")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 820, 481, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 820, 481, 20))
        self.label_2.setObjectName("label_2")
        self.tabWidget_2.raise_()
        self.horizontalFrame.raise_()
        self.tabWidget.raise_()
        self.textEdit_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1191, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_4.setText(_translate("MainWindow", "файл"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_2.setText(_translate("MainWindow", "Проверка"))
        self.checkBox_2.setText(_translate("MainWindow", "Слова"))
        self.checkBox_3.setText(_translate("MainWindow", "Векторы"))
        self.checkBox.setText(_translate("MainWindow", "Комбинации"))
        self.checkBox_4.setText(_translate("MainWindow", "Тематический анализ"))
        self.checkBox_5.setText(_translate("MainWindow", "Распознавание именованных сущностей"))
        self.pushButton_5.setText(_translate("MainWindow", "Старт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница"))
        self.pushButton_6.setText(_translate("MainWindow", "Кнопка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Страница"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Thematical Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "NER"))
        self.toolButton_7.setText(_translate("MainWindow", "Кнопка"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 1"))
        self.checkBox_6.setText(_translate("MainWindow", "Наукоментрические базы"))
        self.checkBox_7.setText(_translate("MainWindow", "Отзывы на вузы"))
        self.pushButton_8.setText(_translate("MainWindow", "Искать"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Tab 2"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Кол-во слов:"))
        self.label_2.setText(_translate("MainWindow", "Время потраченное на выполнение запроса:"))


    def count_words_in_file(self, file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                text = file.read()
                words = text.split()
                return len(words)
        except:
            pass

    def FileChoiceDialogue(self):
        try:
            filename, smth = QFileDialog.getOpenFileName(None, "Выберите файл", "", "All Files (*);;Text Files (*.txt)")
            print(filename, smth)
            type = filename.split(".")[-1]
            if type == "pdf":
                lang, model = self.models[self.comboBox.currentText()]
                print(lang)
                if lang == "ru":
                    print("entered ru")
                    self.ocr.ConvertPDF("rus", filename, "".join(type))
                    print("exited ru")
                if lang == "en":
                    print("entered en")
                    self.ocr.ConvertPDF("eng", filename, "".join(type))
                    print("exited en")
                filename = "".join(type) + ".txt"
            with open(filename, mode="r", encoding="utf-8") as f:
                self.textEdit_2.setText(f.read())
            self.label.setText(f"Кол-во слов: {self.count_words_in_file(filename)}")
        except:
            pass

    def ParsePoly(self):
        self.lineEdit.setText("Московский политех")
        self.textBrowser_4.setText(self.FormatPolytechData(tools.PolytechParser.ParsePolytechData()))

    def FormatPolytechData(self, data):
        text = "\n\n".join(data)
        return text

    def FormatInternet(self, results):
        text = ""
        print("entered Format")
        for title, link, snippet in results:
            text += title + "\n" + link + "\n" + snippet + "\n\n"
        print(text)
        return text

    def ShowGraph(self):
        lang, model = self.models[self.comboBox.currentText()]
        NLP = model
        SortedText, SortedTextVectors = self.GraphDataCollection()
        print(SortedText)
        print(list(SortedText))
        tools.PlottingGraph.PlottingGraph(TextInput=list(SortedText.keys()), TextVectors=SortedTextVectors)
        pixmap = QPixmap("graph.png")
        scene = QGraphicsScene()
        item = QGraphicsPixmapItem(pixmap)
        scene.addItem(item)
        self.graphicsView.setScene(scene)
        self.graphicsView.fitInView(item, Qt.KeepAspectRatio)
        img = Image.open("graph.png")
        img.show()


    def ParseInternet(self):
        text = self.lineEdit.text()
        print(text)
        results = self.searchEngine.getResultsByKeyword(text, 0)
        print(results)
        self.textBrowser_4.setText(self.FormatInternet(self.searchEngine.getResultsByKeyword(text, 0)))

    def save_text_to_file(self, text):
        with open("saved.txt", 'w', encoding='utf-8') as file:
            file.write(text)

    def save(self):
        text = self.textEdit_2.toPlainText()
        self.save_text_to_file(text)

    def RouteParser(self):
        if self.checkBox_7.isChecked():
            print("poly")
            self.ParsePoly()
        else:
            print("cool")
            self.ParseInternet()

    def GetModelLang(self, text):
        print(text)
        if text[0] == "А":
            return ("en", "en_core_web_lg")
        return ("ru", "ru_core_news_lg")

    def FormatWords(self, wordsFreq, back=""):
        formatedText = ""
        for word, freq in wordsFreq.items():
            formatedText += str(word) + ": " + str(freq) + back + "\n"
        return formatedText

    def FormatCombos(self, combosFreq):
        print(type(combosFreq))
        formatedText = ""
        for combo, freq in combosFreq.items():
            print(combo)
            formatedText += " ".join(list(combo)) + ": " + str(freq) + "\n"
        return formatedText

    def ApplyWords(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.models[self.comboBox.currentText()]
        wordsFreq = Words.Words(text, model, lang)
        self.textBrowser_2.setText(self.FormatWords(wordsFreq))

    def GraphDataCollection(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.models[self.comboBox.currentText()]
        NLP = model
        SortedText = Words.Words(text, NLP, lang)
        SortedTextVectors = [NLP(word).vector for word in SortedText]  # List of Numpy arrays
        return (SortedText, SortedTextVectors)

    def ApplyVectors(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.models[self.comboBox.currentText()]
        self.VectorMap = Vectors.VectorsPrecalc(text, model, lang)

    def FindVector(self):
        WordToFindSimilar = self.LineEditVectors.text()
        lang, model = self.models[self.comboBox.currentText()]
        self.TextVectors.setText(self.FormatWords(Vectors.Vectors(self.VectorMap, model, WordToFindSimilar), "%"))

    def ApplyCombos(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.models[self.comboBox.currentText()]
        comboNumber = self.horizontalSlider.value()
        print(comboNumber)
        sortedCombos = Combos.Combos(text, model, lang, comboNumber)
        self.textBrowser_3.setText(self.FormatCombos(sortedCombos))

    def ApplyTA(self):
        text = self.textEdit_2.toPlainText()
        num_topics = self.horizontalSlider_2.value()
        self.textEdit_4.setText(NewLDA.NewLDA(text, num_topics))

    def ApplyNER(self):
        text = self.textEdit_2.toPlainText()
        lang, model = self.models[self.comboBox.currentText()]
        self.textEdit_5.setText(tools.NamedEntryRecognition.ner(text, model))

    def AskDeepSeek(self):
        self.textEdit.setText(tools.DeepSeekRequest.requestDeepSeek(self.plainTextEdit.toPlainText()))

    def route(self):
        try:
            if self.checkBox_2.isChecked():
                self.ApplyWords()
            if self.checkBox_3.isChecked():
                self.ApplyVectors()
            if self.checkBox.isChecked():
                self.ApplyCombos()
            if self.checkBox_4.isChecked():
                self.ApplyTA()
            if self.checkBox_5.isChecked():
                self.ApplyNER()
            self.ShowGraph()
        except:
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
